---
title: "Milestone-2"
author: "David Moberg"
date: "9/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Final project Number 1: Simone Chu's "Presidential Speeches" Project, Spring 2019: [https://simonechu.shinyapps.io/presidentialspeeches/]

Simone Chu's Gov 1005 final project was on presidential addresses: Inaugural, State of the Union, relations with the press, and final words in office. Perhaps the most interesting component, to me, is that Simone's project compares emotion and intent, by classifying and displaying the most common words contained within a given speech, and displaying the emotional progession of a speech. Simone's analysis is interesting, and I do really like this analysis of the data.That having been said, I would love more in-depth analysis of the data, or to have more conclusions drawn. It feels more like this is a display of a high-quality program to find and classify words by emotion in a given text, rather than draw significant conclusions. If I were making this specific project, given time I would hope to make perhaps some comparisons of all presidential inaugural addresses available for example, or change in tone between presidents compared over an extended period. Still though, Simone's project is very interesting, and I do not in any way wish to detract from or criticize the job she did.


Final Project Number 2: Debora Gonzalez, "The Sunshine State Turns Purple on Election Day" [https://debi-gonzalez.shinyapps.io/FL_Population_and_Politics/] 

Debora Gonzalez's 1005 final project, on the political demographics and trends of FLorida, is  intriguing to me for two reasons: 1) because of its content (I'm a gov concentrator, after all) but 2) because its use of graphics (namely, interactive maps) are something that I do not yet know how to do in R/RMarkdown and would very much like to learn how to do. To contrast with the first project, which I said needed more in-depth analysis, or perhaps a broader history/picture, Debora's project feels to me like a very comprehensive picture - it displays an important set of attributes about the world at large, and mostly lets those do the talking. I know these statements aren't really very profound, but thsoe are the things that jump out at me in this project - the maps and statistics provided fit together very well, and the viewer has a good sense of the broader picture, or rather the "stakes" of the project. In addition, quite a lot of data is on hand, having been cleaned and employed in multiple ways. so this is a project I will keep in mind as an example when I need to deal with large datasets. I have found so far that cleaning data has been among the more vexing topics to me in class, so this will be a good reference. There are several iterations of the data in the git folder, that get progressively more organized, with lots of parsing and recasting as numbers, etc. This is the kind of material that I still find confusing in R, so I will likely be returning to this proejct as an example as 1005 progresses.
